@host = localhost
@port = 3000
@apiversion = api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4ODAxMjNhLWQ3YWYtNDEwZC1iZWExLWUzZmIzZjljMWQ1MyIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obnNAY29udG9zby5jb20uYnIiLCJpYXQiOjE3MzIyOTk0ODQsImV4cCI6MTc2MzgzNTQ4NH0.cYhVoAEvpfeu292p-nWO9wtinV9Dm1tY6Dj_PunagNs



###
POST http://{{host}}:{{port}}/{{apiversion}}/organization/create-organization
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "acme",
  "domain": "acme.me",
  "shouldAttachUsersByDomain": false,
  "ownerId": "a671e8e0-a7ec-4035-afc7-a4d7216ca5ee"
}
###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/acme/membership
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/acme
Content-Type: application/json
Authorization: Bearer {{token}}
###
DELETE http://{{host}}:{{port}}/{{apiversion}}/organization/acme
Content-Type: application/json
Authorization: Bearer {{token}}

###
PATCH  http://{{host}}:{{port}}/{{apiversion}}/organization/acme-inc/owner
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/user-organizations
Content-Type: application/json
Authorization: Bearer {{token}}
