@host = localhost
@port = 3000
@apiversion = api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0M2EwMzBmLTNlN2MtNGU4Zi04ZGU0LWY2OTc1MmQ0YWVlZCIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obnNAY29udG9zby5jb20uYnIiLCJpYXQiOjE3MzIxNTM0MTYsImV4cCI6MTc2MzY4OTQxNn0.RD94LAGLZ7o8q4haII2RhSnIlbwSBw6yqLsKDZtOrvA


###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/user-organizations
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://{{host}}:{{port}}/{{apiversion}}/organization/create-organization
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "acme inc",
  "domain": "acmeinc.me",
  "shouldAttachUsersByDomain": false,
  "ownerId": "a671e8e0-a7ec-4035-afc7-a4d7216ca5ee"
}
###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/acmes/membership
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET http://{{host}}:{{port}}/{{apiversion}}/organization/acme
Content-Type: application/json
Authorization: Bearer {{token}}
